# Generated by Django 2.2.5 on 2020-05-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepuser',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
