# Generated by Django 2.2.5 on 2020-05-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200504_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepuser',
            name='icon',
            field=models.ImageField(null=True, upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='nepuser',
            name='mobile',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
