# Generated by Django 2.2.5 on 2020-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200506_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepuser',
            name='discription',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nepuser',
            name='qq_num',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='nepuser',
            name='score',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='nepuser',
            name='icon',
            field=models.ImageField(default='user_icon/default-icon.jpg', null=True, upload_to='user_icon/'),
        ),
    ]
